#!/bin/bash

Digit=6

usage() {
	echo "Usage: $0 [-g <file>] [-k <key>]" >&2
}

main() {
	parse_args "$@"
	if [ -n "$gval" ]; then
		generate_ft_opt
	elif [ -n "$kval" ]; then
		generate_hotp
	else
		usage
		exit 1
	fi
}

parse_args() {
	while getopts 'g:k:' name; do
		case "$name" in
			g) gval="$OPTARG";;
			k) kval="$OPTARG" ;;
			*) usage ; exit 1 ;;
		esac
	done
}

generate_ft_opt() {
	echo '[TODO] Generate ft_otp'
}

generate_hotp() {
	echo '[TODO] Generate HOTP'
}

hotp() {
	local key="$1" counter="$2"
	HS=$(HMAC_SHA_1 "$key" "$counter")
	Sbits="$(DT "$HS")"
	Snum="$(StToNum "$Sbits")"
	D="$((Snum % (10 ** Digit)))"
	echo "$D"
}

HMAC_SHA_1() {
	local key="$1" txt="$2"
	echo -n "$txt" | openssl sha1 -hmac "$key" | cut -f 2 -d ' '
}

DT() {
	String="$(echo -n "$1" | tr '[:lower:]' '[:upper:]')"
	OffsetBits="${String:39:1}"
	Offset="$((16#$OffsetBits * 2))"
	P="${String:$Offset:8}"
	echo "obase=16;ibase=10;$((16#$P & 16#7fffffff))" \
		| bc \
		| tr '[:upper:]' '[:lower:]' \
		| tr -d '\n'
}

StToNum() {
	St="$(echo -n "$1" | tr '[:lower:]' '[:upper:]')"
	echo "obase=10;ibase=16;$St" | bc | tr -d '\n'
}

main "$@"
