#!/bin/bash

usage() {
	echo "Usage: $0 [-g <file>] [-k <key>]" >&2
}

main() {
	parse_args "$@"
	if [ -n "$gval" ]; then
		generate_ft_otp
	elif [ -n "$kval" ]; then
		generate_hotp
	else
		usage
		exit 1
	fi
}

err_msg() {
	echo "$0: error: $1" >&2
}

parse_args() {
	while getopts 'g:k:' name; do
		case "$name" in
			g) gval="$OPTARG";;
			k) kval="$OPTARG" ;;
			*) usage ; exit 2 ;;
		esac
	done
}

crypt() {
	local salt="1acab60b8d1820ec"
	opts=(
		-aes-256-cbc
		-pbkdf2
		-S "$salt"
		-pass file:password
	)
	openssl enc "${opts[@]}" "$@"
}

generate_ft_otp() {
	if ! [ -e "$gval" ]; then
		err_msg "file '$gval' does not exist."
		exit 1
	elif ! cat "$gval" | grep -qE '^[0-9a-fA-F]{64}$'; then
		err_msg "key must be 64 hexadecimal characters."
		exit 1
	fi
	crypt -in "$gval" -out ft_otp.key
	echo "Key was successfully saved in ft_otp.key."
}

generate_hotp() {
	if ! [ -e "$kval" ]; then
		err_msg "file '$kval' does not exist."
		exit 1
	fi
	counter="$(($(date +%s) / 30))"
	bash hotp.sh "$counter" "$(cat key.txt)"
}

main "$@"
